"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Request = exports.Scope = exports.MiddlewareStack = exports.Link = exports.BelongsTo = exports.HasOne = exports.HasMany = exports.Attr = exports.Model = exports.belongsTo = exports.hasOne = exports.hasMany = exports.attr = exports.Attribute = exports.SpraypaintBase = void 0;
var tslib_1 = require("tslib");
var model_1 = require("./model");
Object.defineProperty(exports, "SpraypaintBase", { enumerable: true, get: function () { return model_1.SpraypaintBase; } });
var attribute_1 = require("./attribute");
Object.defineProperty(exports, "Attribute", { enumerable: true, get: function () { return attribute_1.Attribute; } });
Object.defineProperty(exports, "attr", { enumerable: true, get: function () { return attribute_1.attr; } });
var associations_1 = require("./associations");
Object.defineProperty(exports, "hasMany", { enumerable: true, get: function () { return associations_1.hasMany; } });
Object.defineProperty(exports, "hasOne", { enumerable: true, get: function () { return associations_1.hasOne; } });
Object.defineProperty(exports, "belongsTo", { enumerable: true, get: function () { return associations_1.belongsTo; } });
var decorators_1 = require("./decorators");
Object.defineProperty(exports, "Model", { enumerable: true, get: function () { return decorators_1.Model; } });
Object.defineProperty(exports, "Attr", { enumerable: true, get: function () { return decorators_1.Attr; } });
Object.defineProperty(exports, "HasMany", { enumerable: true, get: function () { return decorators_1.HasMany; } });
Object.defineProperty(exports, "HasOne", { enumerable: true, get: function () { return decorators_1.HasOne; } });
Object.defineProperty(exports, "BelongsTo", { enumerable: true, get: function () { return decorators_1.BelongsTo; } });
Object.defineProperty(exports, "Link", { enumerable: true, get: function () { return decorators_1.Link; } });
var middleware_stack_1 = require("./middleware-stack");
Object.defineProperty(exports, "MiddlewareStack", { enumerable: true, get: function () { return middleware_stack_1.MiddlewareStack; } });
var scope_1 = require("./scope");
Object.defineProperty(exports, "Scope", { enumerable: true, get: function () { return scope_1.Scope; } });
var request_1 = require("./request");
Object.defineProperty(exports, "Request", { enumerable: true, get: function () { return request_1.Request; } });
tslib_1.__exportStar(require("./jsonapi-spec"), exports);
//# sourceMappingURL=index.js.map