name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test [Node, TypeScript]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
        ts-version:
          # - '3.3'
          - '3.4'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '4.0'
          - '4.1'
          - '4.2'
          - '4.3'
          - '4.4'
          - '4.5'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use TypeScript ${{ matrix.ts-version }}
        run: yarn add --dev typescript@${{ matrix.ts-version }}
      - name: Use specific TS chai types for ts${{ matrix.ts-version }}
        run: yarn add --dev @types/chai@ts${{ matrix.ts-version }}
      - name: Install
        run: yarn install
      - name: Run Lint
        run: yarn lint:ci
      - name: Run Tests
        run: yarn test:ci
